"""empty message

Revision ID: 126d60e13a98
Revises: b7a319a4eee8
Create Date: 2017-03-18 21:50:55.547248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '126d60e13a98'
down_revision = 'b7a319a4eee8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('pmid', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('abstract', sa.String(length=2000), nullable=True),
    sa.Column('created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lastmodified', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_articles')
    # ### end Alembic commands ###
