"""empty message

Revision ID: b7a319a4eee8
Revises: 08cae6646bd0
Create Date: 2017-03-18 21:28:17.870546

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b7a319a4eee8'
down_revision = '08cae6646bd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('articles')
    op.drop_table('last_pmid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('last_pmid',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('record_date', mysql.DATETIME(), nullable=True),
    sa.Column('pmid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table('articles',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('pmid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('abstract', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    # ### end Alembic commands ###
