"""empty message

Revision ID: c89b45e1d613
Revises: b8cfdf6208df
Create Date: 2017-03-18 11:21:47.148200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c89b45e1d613'
down_revision = 'b8cfdf6208df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recommend_articles', sa.Column('title_1', sa.String(length=200), nullable=True))
    op.add_column('recommend_articles', sa.Column('title_10', sa.String(length=200), nullable=True))
    op.add_column('recommend_articles', sa.Column('title_2', sa.String(length=200), nullable=True))
    op.add_column('recommend_articles', sa.Column('title_3', sa.String(length=200), nullable=True))
    op.add_column('recommend_articles', sa.Column('title_4', sa.String(length=200), nullable=True))
    op.add_column('recommend_articles', sa.Column('title_5', sa.String(length=200), nullable=True))
    op.add_column('recommend_articles', sa.Column('title_6', sa.String(length=200), nullable=True))
    op.add_column('recommend_articles', sa.Column('title_7', sa.String(length=200), nullable=True))
    op.add_column('recommend_articles', sa.Column('title_8', sa.String(length=200), nullable=True))
    op.add_column('recommend_articles', sa.Column('title_9', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recommend_articles', 'title_9')
    op.drop_column('recommend_articles', 'title_8')
    op.drop_column('recommend_articles', 'title_7')
    op.drop_column('recommend_articles', 'title_6')
    op.drop_column('recommend_articles', 'title_5')
    op.drop_column('recommend_articles', 'title_4')
    op.drop_column('recommend_articles', 'title_3')
    op.drop_column('recommend_articles', 'title_2')
    op.drop_column('recommend_articles', 'title_10')
    op.drop_column('recommend_articles', 'title_1')
    # ### end Alembic commands ###
